apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
spec:
  ingressClassName: nginx
  rules:
    - host: UPDATE_HOST
      http:
        paths:
          - backend:
              service:
                name: jenkins-qa
                port:
                  number: 8080
            path: /
            pathType: Prefix